spring.application.name=LegacyLoomAi


springdoc.swagger-ui.path=/swagger-ui
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/api-docs
spring.main.allow-bean-definition-overriding=true

gemini.api.key = AIzaSyAulFQ3tiCAD2gzlFdJ48m1PxTsNyQv02M
google.gemini.url = https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-preview-tts:generateContent

spring.h2.console.enabled=true

spring.datasource.url=jdbc:h2:mem:AudioDb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

cloudinary.cloud_name=dcwr8fxdz
cloudinary.api_key=646228198237199
cloudinary.api_secret=MpuNgUl7-j9k1Xr4V8Coo8_onSw
